name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          gradle-version: 8.10.2

      - name: Decode local.properties
        env:
          PROPERTIES_BASE_64: ${{ secrets.PROPERTIES_BASE_64 }}
        run: |
          echo $PROPERTIES_BASE_64 > base64.txt
          base64 -d base64.txt >> local.properties

      - name: Build
        run: ./gradlew assembleDebug